apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: cc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cc-api
  name: cc-api
  namespace: cc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cc-api
  template:
    metadata:
      annotations:
        istio-injection: enabled
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"           
      labels:
        app: cc-api
        name: cc-api
        version: v1
    spec:
      containers:
      - name: cc-api
        image: fidelissauro/dr-cc-api:latest
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /readiness
            port: 8080
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /liveness
            port: 8080
          periodSeconds: 10
        env:
        - name: CHAOS_MONKEY_ENABLED
          value: "true"  
        - name: CHAOS_MONKEY_MODE
          value: "critical" 
        - name: CHAOS_MONKEY_LATENCY
          value: "true"            
        - name: CHAOS_MONKEY_EXCEPTION
          value: "true"   
        - name: CHAOS_MONKEY_APP_KILLER
          value: "true"   
        - name: CHAOS_MONKEY_MEMORY
          value: "true"
        - name: CC_API_HOST
          value: http://api.cc.k8s.cluster:80
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: cc-api
  namespace: cc   
  labels:
    app.kubernetes.io/name: cc-api
    app.kubernetes.io/instance: cc-api 
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: cc-api
  type: ClusterIP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cc-api
  namespace: cc
spec:
  maxReplicas: 12
  minReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cc-api
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cc-api-gateway
  namespace: cc
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "api.cc.k8s.cluster"
    - "cc-api.cc.svc.cluster.local"    
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cc-api
  namespace: cc
spec:
  hosts:
  - "api.cc.k8s.cluster"
  - "cc-api.cc.svc.cluster.local"  
  gateways:
  - cc-api-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: cc-api
        port:
          number: 8080
