apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: cc-pod-failure
  namespace: cc
spec:
  action: pod-failure
  mode: fixed-percent
  value: "90"
  duration: "30s"
  selector:
    labelSelectors:
      "app": "cc-api"