apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: clients-pod-failure
  namespace: clients
spec:
  action: pod-failure
  mode: fixed-percent
  value: "50"
  duration: "60s"
  selector:
    labelSelectors:
      "app": "clients-api"