{
 "title": "SLOs - Talk Istio",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "orders-api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Orders API - Ops/Sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{destination_workload=~\"orders-api\"}[1m])) by (response_code)",
       "legendFormat": "{{ response_code }} "
      }
     ]
    },
    {
     "title": "Orders API - Response Flags",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{destination_workload=~\"orders-api\", response_flags!=\"-\"}[1m])) by (response_flags)",
       "legendFormat": "{{ response_flags }} "
      }
     ]
    },
    {
     "title": "Orders API - Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{destination_service=~\"orders-api.orders.svc.cluster.local\"}[$__interval])),0.001)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Orders API - Client Success",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=~\"destination|source\",destination_service=~\"orders-api.orders.svc.cluster.local\",response_code!~\"5.*\"}[5m]))/ sum(irate(istio_requests_total{reporter=~\"destination|source\",destination_service=~\"orders-api.orders.svc.cluster.local\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Orders API - Server Availability",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=~\"destination\",destination_service=~\"orders-api.orders.svc.cluster.local\",response_code!~\"5.*\"}[5m]))/ sum(irate(istio_requests_total{reporter=~\"destination\",destination_service=~\"orders-api.orders.svc.cluster.local\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage / Seconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"orders\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Orders - Memory Usage (w/o cache)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"orders\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "clients-api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clients API - Ops/Sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{destination_workload=~\"clients-api\"}[1m])) by (response_code)",
       "legendFormat": "{{ response_code }} "
      }
     ]
    },
    {
     "title": "Clients API - Response Flags",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{destination_workload=~\"clients-api\", response_flags!=\"-\"}[1m])) by (response_flags)",
       "legendFormat": "{{ response_flags }} "
      }
     ]
    },
    {
     "title": "Clients API - Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{destination_workload=~\"clients-api\"}[$__interval])),0.001)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Clients API - Client Success",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=~\"destination|source\",destination_workload=~\"clients-api\",response_code!~\"5.*\"}[5m]))/ sum(irate(istio_requests_total{reporter=~\"destination|source\",destination_workload=~\"clients-api\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Clients API - Server Availability",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=~\"destination\",destination_workload=~\"clients-api\",response_code!~\"5.*\"}[5m]))/ sum(irate(istio_requests_total{reporter=~\"destination\",destination_workload=~\"clients-api\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Clients - CPU Usage / Seconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"clients\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Clients - Memory Usage (w/o cache)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"clients\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "payments-api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Payment API - Ops/Sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{destination_workload=~\"payment-api\"}[1m])) by (response_code)",
       "legendFormat": "{{ response_code }} "
      }
     ]
    },
    {
     "title": "Payments API - Response Flags",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{destination_workload=~\"payment-api\", response_flags!=\"-\"}[1m])) by (response_flags)",
       "legendFormat": "{{ response_flags }} "
      }
     ]
    },
    {
     "title": "Payment API - Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{destination_workload=~\"payment-api\"}[$__interval])),0.001)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Payment API - Client Success",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=~\"destination|source\",destination_workload=~\"payment-api\",response_code!~\"5.*\"}[5m]))/ sum(irate(istio_requests_total{reporter=~\"destination|source\",destination_workload=~\"payment-api\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Payment API - Server Availability",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=~\"destination\",destination_workload=~\"payment-api\",response_code!~\"5.*\"}[5m]))/ sum(irate(istio_requests_total{reporter=~\"destination\",destination_workload=~\"payment-api\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Payments - CPU Usage / Seconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"payment\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Payments - Memory Usage (w/o cache)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"payment\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "cc-api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CC API - Ops/Sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{destination_workload=~\"cc-api\"}[1m])) by (response_code)",
       "legendFormat": "{{ response_code }} "
      }
     ]
    },
    {
     "title": "CC API - Response Flags",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{destination_workload=~\"cc-api\", response_flags!=\"-\"}[1m])) by (response_flags)",
       "legendFormat": "{{ response_flags }} "
      }
     ]
    },
    {
     "title": "CC API - Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{destination_workload=~\"cc-api\"}[$__interval])),0.001)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CC API - Client Success",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=~\"destination|source\",destination_workload=~\"cc-api\",response_code!~\"5.*\"}[5m]))/ sum(irate(istio_requests_total{reporter=~\"destination|source\",destination_workload=~\"cc-api\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Clients API - Server Availability",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=~\"destination\",destination_workload=~\"cc-api\",response_code!~\"5.*\"}[5m]))/ sum(irate(istio_requests_total{reporter=~\"destination\",destination_workload=~\"cc-api\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CC - CPU Usage / Seconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"cc\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CC - Memory Usage (w/o cache)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"cc\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}