apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: orders
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders-api
  name: orders-api
  namespace: orders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      annotations:
        istio-injection: enabled
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"           
      labels:
        app: orders-api
        name: orders-api
        version: v1
    spec:
      containers:
      - name: orders-api
        image: fidelissauro/dr-orders-api:latest
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        startupProbe:
          successThreshold: 1
          failureThreshold: 10
          httpGet:
            path: /readiness
            port: 8080
          periodSeconds: 10
        livenessProbe:
          successThreshold: 1
          failureThreshold: 10
          httpGet:
            path: /liveness
            port: 8080
          periodSeconds: 10
        env:
        - name: CHAOS_MONKEY_ENABLED
          value: "false"  
        - name: CHAOS_MONKEY_MODE
          value: "critical" 
        - name: CHAOS_MONKEY_LATENCY
          value: "true"            
        - name: CHAOS_MONKEY_EXCEPTION
          value: "true"   
        - name: CHAOS_MONKEY_APP_KILLER
          value: "true"   
        - name: CHAOS_MONKEY_MEMORY
          value: "false"
        - name: CHAOS_MONKEY_CPU
          value: "false"
        - name: CHAOS_MONKEY_LATENCY_MIN_TIME
          value: "2000"
        - name: CHAOS_MONKEY_LATENCY_MAX_TIME
          value: "5000"          
        - name: PAYMENT_API_HOST
          value: http://payment-api.payment.svc.cluster.local:8080
        - name: CLIENTS_API_HOST
          value: http://clients-api.clients.svc.cluster.local:8080        
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api
  namespace: orders   
  labels:
    app.kubernetes.io/name: orders-api
    app.kubernetes.io/instance: orders-api 
spec:
  ports:
  - name: http-web
    port: 8080
    protocol: TCP
  selector:
    app: orders-api
  type: ClusterIP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: orders-api
  namespace: orders
spec:
  maxReplicas: 12
  minReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders-api
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: orders-api-gateway
  namespace: orders
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "api.orders.k8s.cluster"
    - "orders-api.orders.svc.cluster.local"    
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: orders-api
  namespace: orders
spec:
  hosts:
  - "api.orders.k8s.cluster"
  gateways:
  - orders-api-gateway
  http:
  - route:
    - destination:
        host: orders-api
        port:
          number: 8080
    retries:
      attempts: 5
      perTryTimeout: 500ms
      retryOn: 5xx,gateway-error,connect-failure,refused-stream          
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: orders-api-internal
  namespace: orders
spec:
  hosts:
  - "orders-api.orders.svc.cluster.local"  
  http:
  - route:
    - destination:
        host: orders-api
        port:
          number: 8080
    retries:
      attempts: 5
      perTryTimeout: 500ms
      retryOn: 5xx,gateway-error,connect-failure,refused-stream,reset,resource-exhausted,unavailable,cancelled
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: orders
  namespace: orders
spec:
  host: orders-api.orders.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 500
      http:
        http1MaxPendingRequests: 30
        maxRequestsPerConnection: 100
    outlierDetection:
      consecutive5xxErrors: 2
      interval: 300ms
      baseEjectionTime: 60s
      maxEjectionPercent: 100