apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: payment-pod-failure
  namespace: payment
spec:
  action: pod-failure
  mode: fixed-percent
  value: "90"
  duration: "30s"
  selector:
    labelSelectors:
      "app": "payment-api"