apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: clients-pod-kill
  namespace: clients
spec:
  action: pod-kill
  mode: fixed-percent
  value: "50"
  duration: "60s"
  selector:
    namespaces:
      - clients
    labelSelectors:
      "app": "clients-api"