apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: payment-pod-kill
  namespace: payment
spec:
  action: pod-kill
  mode: fixed-percent
  value: "50"
  duration: "60s"
  selector:
    namespaces:
      - payment
    labelSelectors:
      "app": "payment-api"